### ISSUE TITLE
Can we add getPlaces or some way to control the `types` param in reverse geo-coding? 

### ISSUE THREAD

**Issue by Kacppian** [ketanchoyal/mapbox_search#29]
I basically want to be able to get all places associated with a pair of lat, lng as getting an address isn't always possible.

**Comment by Kacppian** [comment]
👍

**Comment by ketanchoyal** [comment]
I guess you can get it by using reverse geo, there is a function for that too

**Comment by Kacppian** [comment]
I was using the reverse geo function but it doesn’t allow for specifying the types of locations to be returned based on the coords

**Comment by ketanchoyal** [comment]
Closing because of no further development on this topic
