### ISSUE TITLE
reverseGeoCoding.getAddress not working

### ISSUE THREAD

**Issue by satyajitghana** [ketanchoyal/mapbox_search#34]
Hey, i was just checking out the getAddress function in README

```dart
    List<MapBoxPlace> places = await reverseGeoCoding.getAddress(
      Location(lat: 72.0, lng: 76.00),
    );
```

but even this returns 0 results, almost all coordinates return 0 results, something up with the API changes ?

**Comment by threetwotwo** [comment]
Same here

**Comment by ketanchoyal** [comment]
Sorry, @satyajitghana and @threetwotwo for the late reply, I'll look into this problem as soon as possible

**Comment by ketanchoyal** [comment]
have you guys tried any other location coordinates?

**Comment by satyajitghana** [comment]
> have you guys tried any other location coordinates? 

yes, same problem, is it a mapbox issue ?

**Comment by ChiragKr04** [comment]
Well same issue for me some coordinated work but some give blank output.


      // These Work
       var addresses = await geoCodingService.getAddress(
            Location(
              lat: 51.5074,
              lng: 0.1278,
            ),
          );
      print("newaddr:$addresses");

      // These Not
          var addresses = await geoCodingService.getAddress(
      Location(
        lat: 72.00,
        lng: 76.00,
      ),
    );

    print("newaddr:$addresses");

**Comment by ChiragKr04** [comment]
> > have you guys tried any other location coordinates?
> 
> yes, same problem, is it a mapbox issue ?

I guess so for some coordinate works but for some coordinates, it won't

**Comment by ketanchoyal** [comment]
According to me MapBox don't have as much data as google maps have for some places

**Comment by satyajitghana** [comment]
> According to me MapBox don't have as much data as google maps have for some places

I agree, so I moved to google maps, it's so much better.
Mapbox doesn't have Indian maps that well compared to google maps.
