### ISSUE TITLE
Is there any way to get city name of a address ?

### ISSUE THREAD

**Issue by developmentkws** [ketanchoyal/mapbox_search#55]
as of now we can get ,
  
  `String id;
  FeatureType type;
  List<PlaceType> placeType;
  String addressNumber;
  Properties properties;
  String text;
  String placeName;
  List<double> bbox;
  List<double> center;
  Geometry geometry;
  List<Context> context;
  String matchingText;
  String matchingPlaceName;`

please add way to get city too. please

**Comment by ketanchoyal** [comment]
There is an object called context in the response, it should have everything you need
