### ISSUE TITLE
is ReverseGeoCoding not working ?

### ISSUE THREAD

**Issue by Oct7** [ketanchoyal/mapbox_search#59]
ReverseGeoCoding reverseGeoCoding = ReverseGeoCoding(
      apiKey: dotenv.env['mapbox_access_token'],
      country: "KR",
      language: 'ko',
      limit: 10,
      types: PlaceType.address,
    );

    List<MapBoxPlace> list = await reverseGeoCoding.getAddress(
      Location(
        lat: Get.find<PlaceMapUpdateController>().map_controller.cameraPosition.target.latitude,
        lng: Get.find<PlaceMapUpdateController>().map_controller.cameraPosition.target.longitude,
      ),
    );
 print(list);

this is my code, but it returns []

how can i solve it ?

**Comment by ketanchoyal** [comment]
this might be related to issue #34
