### ISSUE TITLE
Any functionality to prioritize nearby locations?

### ISSUE THREAD

**Issue by cybertheory** [ketanchoyal/mapbox_search#62]
Just wondering if there were plans to list nearby locations on the top of search? Mapbox API should support this...

**Comment by ketanchoyal** [comment]
can you please provide the documentation link for mapbox api, I can take a look and if it's straight forward I might do it over the weekend, I don't get enough time to look and add new features

And if you can implement it and make a PR to `dev` branch that would be awesome

**Comment by cybertheory** [comment]
Just checked and they don't support for geocoding, but they do have search API beta. Let me know if you need help implementing that!

**Comment by cybertheory** [comment]
Hey Noticed you were implementing Proximity,

I think we can just send a pair of coordinates, perhaps we could add to getplaces function?

https://docs.mapbox.com/help/tutorials/local-search-geocoding-api/
