### ISSUE TITLE
geometry and center fields in MabBoxPlace have long first then lat

### ISSUE THREAD

**Issue by cybertheory** [ketanchoyal/mapbox_search#66]
Is this is the correct behavior?
I was using mapbox_gl package in flutter to map a location I found through this package, but I had to flip the coordinates in the geometry object. Otherwise I ended up in antartica!

**Comment by ketanchoyal** [comment]
those are just the list of coordinates we get from mapbox api, there is no mapping in the package it is just passsed as list, user has to figure out which one is lat and long.

You are happy to make a PR, I can merge it if it passes all the test cases

**Comment by cybertheory** [comment]
Ok will take a look

**Comment by ketanchoyal** [comment]
@cybertheory  This was handled in the latest release
