### ISSUE TITLE
Update http pubspec

### ISSUE THREAD

**Issue by moshOntong-IT** [ketanchoyal/mapbox_search#70]
Because mapbox_search >=3.0.0-nullsafety.0 <4.0.0-beta.2 depends on http ^0.13.0 and google_fonts >=4.0.5 depends on http ^1.0.0, mapbox_search >=3.0.0-nullsafety.0 <4.0.0-beta.2 is incompatible with google_fonts >=4.0.5.
So, because tiktak_app depends on both google_fonts ^5.0.0 and mapbox_search ^3.2.0, version solving failed.

**Comment by Flajt** [comment]
See #73 I've created a PR, this should fix it I think

**Comment by MrLongg71** [comment]
Can you review and merge PR 73 to fix this? @ketanchoyal

**Comment by ketanchoyal** [comment]
Done
