### ISSUE TITLE
Search still doesn't work 

### ISSUE THREAD

**Issue by Alexey47836** [ketanchoyal/mapbox_search#87]
Unfortunately the search still doesn't work after your new version 4.2.1. It’s just that where you want to cast to some type, if the server returns null, that’s where it will fail. You need to make changes to the Models:

1. In the file "location_context.g.dart" you need to change the line "regionCode: json['region_code'] as String" in line 60 to "regionCode: json['region_code'] == null ? null : json['region_code '] as String,"

2. In the file "location_context.dart" you need to change the line "final String regionCode;" in line 63 to "final String? regionCode;"

3. In the file "suggestion_response.g.dart" you need to change the line "externalIds: ExternalIds.fromJson(json['external_ids'] as Map<String, dynamic>)," in line 38, to "externalIds: json['external_ids'] == null ? null : ExternalIds.fromJson(json['external_ids'] as Map<String, dynamic>),"

**Comment by ketanchoyal** [comment]
What are the steps to reproduce this bug

**Comment by Alexey47836** [comment]
First, I initialize the SearchBoxAPI and then, at the user’s request, I try to get suggestions in the search, but I can’t do anything because everything falls in the places I described above. Have you added a "?" to the ExternalIds type? but at this point: "externalIds: ExternalIds.fromJson(json['external_ids'] as Map<String, dynamic>),", you are still doing a forced cast to a type without checking for null. This is an error because it is in this place that if there is no check for null, everything will fail and your code will stop executing.
<img width="1419" alt="Screenshot 2024-01-22 at 01 11 31" src="https://github.com/ketanchoyal/mapbox_search/assets/58269242/87fc471a-998a-4366-979f-4aaada39def1">

**Comment by ketanchoyal** [comment]
@Alexey47836 this should be fixed in latest release

**Comment by Alexey47836** [comment]
@ketanchoyal  Thanks a lot
